### ISSUE TITLE
It does not allow entering phone number when creating a new record

### ISSUE THREAD

**Issue by kwu022** [BenediktBergmann/PCF-Controls#19] opened 2020-06-11 09:18 UTC
After I upgraded it to the latest v1.9.2.0 version, strange things happen. All phone number fields (both mandatory and optional phone fields) with value display Invalid Phone Number error message when open an existing account record. And all mandatory phone number fields don't allow entering value when creating a new account record (optional ones are fine). It just clears the value when I enter numbers. 

With v1.9.1.0, it sometimes displays no value in the phone number field when open an existing account record. The value displays if I click the Refresh button. However, once I refresh it to get it to work, it seems all other records can open without problem. I can replicate this using Incognito windows since it doesn't cache anything.

**Comment by BenediktBergmann** [comment] 2020-06-12 06:26
I was able to reproduce the second part of your issue (problem with the mandatory field when creating a new record).
This should be fixed in the new version (1.9.3.0) I just released.

Unfortunately, I was not able to reproduce the first error. Are you sure that the numbers really are correct? Do they have the country code prefixed (for example +46 for Sweden)? If they don't have the country code prefixed and you have not configured a default Country code the PCF is not able to parse the number correctly, therefore it will show an error.

**Comment by WhiteyC** [comment] 2020-06-24 01:45
Fax fields are not set as format "phone" but plain text. How can we make the control available for fax fields as they technically are phone numbers?

**Comment by BenediktBergmann** [comment] 2020-07-01 05:52
@WhiteyC: Thanks for the comment. That is a valid point and I will take a look at it. Could you please create a separate issue, since it is not related to the problem @kwu022 has.

**Comment by BenediktBergmann** [comment] 2020-09-14 13:45
No answer after 3 month.

**Closed by BenediktBergmann** 2020-09-14 13:45 UTC
